spring:
  # thymeleaf模式
  thymeleaf:
    mode: HTML
  # 国际化配置
  messages:
    basename: i18n/messages
    encoding: UTF-8
  # 多文件配置
  profiles:
    active: dev

# 头像地址
comment.avatar: /images/avatar.png
blog.user.avatar: /images/avatar.png